- name: Demo tags
  hosts: localhost
  connection: local
  tasks:
    - name: Install Nginx
      ansibile.builtin.debug:
        msg: Installed Nginx
      tags:
        - install

    - name: Start Nginx
      ansibile.builtin.debug:
        msg: Started Nginx
      tasks:
        - service
        - systemd
